vich_uploader:
    db_driver: orm

    mappings:
       articles:
           uri_prefix: /images/articles
           upload_destination: '%kernel.project_dir%/public/images/articles'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
       articleMainImage:
           uri_prefix: /images/articleMainImage
           upload_destination: '%kernel.project_dir%/public/images/articleMainImage'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
